package com.rcibanque.rcidirect.services.core.system.domain;

import java.io.Serializable;

public enum Function implements Serializable {


	PRODUCT_RATE_VARIATION_IN_SCHEDULES(10007),
	REGISTRATION_CHASSIS_VALIDATION(10010),
	UNDERWRITING_TOLERANCE_REAPPROVAL(10112),
	SUITABILITY_SURVEY_DISPLAY(10210),
	DISPLAY_ACCEPTED_EXPOSURE_AMOUNT(10219),
	SEPARATE_DEALER_INVOICE_AND_COMMISSIONS_PAYMENT_FROM_ACTIVATION(10309),
	EURIBOR(10812),
	ALLOW_FINANCED_AMOUNT_MINUS_BALLOON_NULL(11002),
	APPLY_VIN_VERIFICATION(11029),
	COMMISSION_USE_INCL_VAT_FINANCED_AMOUNT(11000),
	APR_DEALER_SCALE(11022),
	APR_SCALE_RATE_UPDATABLE(11025),
	DCR_RATE_VARIATION_ON_SCALE_RATE(11037),
	NON_RV_BALLOON_BASED_ON_EXCL_VAT_AMOUNT(10312),
	BALLOON_VEHICLE_AMOUNT_IS_OPERATION_AMOUNT(11008),
	ENABLE_FRONT_OFFICE_BACK_OFFICE_MESSAGING(12013),
	ENABLE_SENIOR_MESSAGING(12046),
	AGREEMENT_CODE_PATTERN_NEW(10902),
	RV_BALLOON_PERCENTAGE_CALCULATION(16006),
	REMOTE_CUSTOMER(10208),
	ANTI_MONEY_LAUNDERING_CHECK(17000),
	BKR_CREDIT_CHECK(16501),
	CREDIT_CHECK_EXCLUDE_DIRECTORS(15003),
	AGREEMENT_GROUP_MANAGEMENT_ALLOWED_FROM_FRONT_OFFICE(11323),
	TERMINATION_FROM_OUTSTANDING(12034);

	private final Integer _code;

	private Function(Integer pCode) {
		_code = pCode;
	}

	public Integer getCode() {
		return _code;
	}


	public static Function valueOf(Integer pFunctionCode) {
		Function res = null;
		for(Function function : Function.values()) {
			if(function.getCode().equals(pFunctionCode)) {
				res = function;
				break;
			}
		}
		return res;
	}
}
