//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressesOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressesOutputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="Address" type="{urn:crif-creditbureau:v1}AddressOutputType"/&gt;
 *         &lt;element name="AddressDesc" type="{urn:crif-creditbureau:v1}AddressDescType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressesOutputType", propOrder = {
    "address",
    "addressDesc"
})
public class AddressesOutputType {

    @XmlElement(name = "Address")
    protected AddressOutputType address;
    @XmlElement(name = "AddressDesc")
    protected AddressDescType addressDesc;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressOutputType }
     *     
     */
    public AddressOutputType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressOutputType }
     *     
     */
    public void setAddress(AddressOutputType value) {
        this.address = value;
    }

    /**
     * Gets the value of the addressDesc property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescType }
     *     
     */
    public AddressDescType getAddressDesc() {
        return addressDesc;
    }

    /**
     * Sets the value of the addressDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescType }
     *     
     */
    public void setAddressDesc(AddressDescType value) {
        this.addressDesc = value;
    }

}
