//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AlertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlertType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Subject" type="{urn:crif-creditbureau:v1}SubjectNameType"/&gt;
 *         &lt;element name="Contract" type="{urn:crif-creditbureau:v1}ContractAlertType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="DownloadedFlag" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="InsertionEventDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="AlertCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AlertCodeDesc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="UserCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertType", propOrder = {
    "subject",
    "contract"
})
public class AlertType {

    @XmlElement(name = "Subject", required = true)
    protected SubjectNameType subject;
    @XmlElement(name = "Contract", required = true)
    protected ContractAlertType contract;
    @XmlAttribute(name = "DownloadedFlag", required = true)
    protected boolean downloadedFlag;
    @XmlAttribute(name = "InsertionEventDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar insertionEventDate;
    @XmlAttribute(name = "AlertCode", required = true)
    protected String alertCode;
    @XmlAttribute(name = "AlertCodeDesc", required = true)
    protected String alertCodeDesc;
    @XmlAttribute(name = "BranchCode")
    protected String branchCode;
    @XmlAttribute(name = "UserCode")
    protected String userCode;

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectNameType }
     *     
     */
    public SubjectNameType getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectNameType }
     *     
     */
    public void setSubject(SubjectNameType value) {
        this.subject = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link ContractAlertType }
     *     
     */
    public ContractAlertType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractAlertType }
     *     
     */
    public void setContract(ContractAlertType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the downloadedFlag property.
     * 
     */
    public boolean isDownloadedFlag() {
        return downloadedFlag;
    }

    /**
     * Sets the value of the downloadedFlag property.
     * 
     */
    public void setDownloadedFlag(boolean value) {
        this.downloadedFlag = value;
    }

    /**
     * Gets the value of the insertionEventDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsertionEventDate() {
        return insertionEventDate;
    }

    /**
     * Sets the value of the insertionEventDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsertionEventDate(XMLGregorianCalendar value) {
        this.insertionEventDate = value;
    }

    /**
     * Gets the value of the alertCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertCode() {
        return alertCode;
    }

    /**
     * Sets the value of the alertCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertCode(String value) {
        this.alertCode = value;
    }

    /**
     * Gets the value of the alertCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertCodeDesc() {
        return alertCodeDesc;
    }

    /**
     * Sets the value of the alertCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertCodeDesc(String value) {
        this.alertCodeDesc = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the userCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * Sets the value of the userCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCode(String value) {
        this.userCode = value;
    }

}
