//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicationDBType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationDBType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Application" type="{urn:crif-creditbureau:v1}AUE_ApplicationType"/&gt;
 *         &lt;element name="ApplicationDesc" type="{urn:crif-creditbureau:v1}ApplicationDescType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationDBType", propOrder = {
    "application",
    "applicationDesc"
})
public class ApplicationDBType {

    @XmlElement(name = "Application", required = true)
    protected AUEApplicationType application;
    @XmlElement(name = "ApplicationDesc")
    protected ApplicationDescType applicationDesc;

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link AUEApplicationType }
     *     
     */
    public AUEApplicationType getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link AUEApplicationType }
     *     
     */
    public void setApplication(AUEApplicationType value) {
        this.application = value;
    }

    /**
     * Gets the value of the applicationDesc property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationDescType }
     *     
     */
    public ApplicationDescType getApplicationDesc() {
        return applicationDesc;
    }

    /**
     * Sets the value of the applicationDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationDescType }
     *     
     */
    public void setApplicationDesc(ApplicationDescType value) {
        this.applicationDesc = value;
    }

}
