//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 04:47:12 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicationCodesInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationCodesInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ProviderContractNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProviderApplicationNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CBContractCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationCodesInputType")
public class ApplicationCodesInputType {

    @XmlAttribute(name = "ProviderContractNo")
    protected String providerContractNo;
    @XmlAttribute(name = "ProviderApplicationNo")
    protected String providerApplicationNo;
    @XmlAttribute(name = "CBContractCode")
    protected String cbContractCode;

    /**
     * Gets the value of the providerContractNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderContractNo() {
        return providerContractNo;
    }

    /**
     * Sets the value of the providerContractNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderContractNo(String value) {
        this.providerContractNo = value;
    }

    /**
     * Gets the value of the providerApplicationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderApplicationNo() {
        return providerApplicationNo;
    }

    /**
     * Sets the value of the providerApplicationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderApplicationNo(String value) {
        this.providerApplicationNo = value;
    }

    /**
     * Gets the value of the cbContractCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBContractCode() {
        return cbContractCode;
    }

    /**
     * Sets the value of the cbContractCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBContractCode(String value) {
        this.cbContractCode = value;
    }

}
