//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicationUpdatedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationUpdatedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice minOccurs="0"&gt;
 *         &lt;element name="Instalment" type="{urn:crif-creditbureau:v1}InstalmentApplicationUpdatedType"/&gt;
 *         &lt;element name="NonInstalment" type="{urn:crif-creditbureau:v1}NonInstalmentApplicationUpdatedType"/&gt;
 *         &lt;element name="CreditCard" type="{urn:crif-creditbureau:v1}CreditCardApplicationUpdatedType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="ContractPhase" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ContractPhaseDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CurrencyDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CancellationFlag" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MOFLinkCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationUpdatedType", propOrder = {
    "instalment",
    "nonInstalment",
    "creditCard"
})
public class ApplicationUpdatedType {

    @XmlElement(name = "Instalment")
    protected InstalmentApplicationUpdatedType instalment;
    @XmlElement(name = "NonInstalment")
    protected NonInstalmentApplicationUpdatedType nonInstalment;
    @XmlElement(name = "CreditCard")
    protected CreditCardApplicationUpdatedType creditCard;
    @XmlAttribute(name = "ContractPhase")
    protected String contractPhase;
    @XmlAttribute(name = "Currency")
    protected String currency;
    @XmlAttribute(name = "ContractPhaseDesc")
    protected String contractPhaseDesc;
    @XmlAttribute(name = "CurrencyDesc")
    protected String currencyDesc;
    @XmlAttribute(name = "CancellationFlag")
    protected String cancellationFlag;
    @XmlAttribute(name = "MOFLinkCode")
    protected String mofLinkCode;

    /**
     * Gets the value of the instalment property.
     * 
     * @return
     *     possible object is
     *     {@link InstalmentApplicationUpdatedType }
     *     
     */
    public InstalmentApplicationUpdatedType getInstalment() {
        return instalment;
    }

    /**
     * Sets the value of the instalment property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstalmentApplicationUpdatedType }
     *     
     */
    public void setInstalment(InstalmentApplicationUpdatedType value) {
        this.instalment = value;
    }

    /**
     * Gets the value of the nonInstalment property.
     * 
     * @return
     *     possible object is
     *     {@link NonInstalmentApplicationUpdatedType }
     *     
     */
    public NonInstalmentApplicationUpdatedType getNonInstalment() {
        return nonInstalment;
    }

    /**
     * Sets the value of the nonInstalment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonInstalmentApplicationUpdatedType }
     *     
     */
    public void setNonInstalment(NonInstalmentApplicationUpdatedType value) {
        this.nonInstalment = value;
    }

    /**
     * Gets the value of the creditCard property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardApplicationUpdatedType }
     *     
     */
    public CreditCardApplicationUpdatedType getCreditCard() {
        return creditCard;
    }

    /**
     * Sets the value of the creditCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardApplicationUpdatedType }
     *     
     */
    public void setCreditCard(CreditCardApplicationUpdatedType value) {
        this.creditCard = value;
    }

    /**
     * Gets the value of the contractPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractPhase() {
        return contractPhase;
    }

    /**
     * Sets the value of the contractPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractPhase(String value) {
        this.contractPhase = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the contractPhaseDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractPhaseDesc() {
        return contractPhaseDesc;
    }

    /**
     * Sets the value of the contractPhaseDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractPhaseDesc(String value) {
        this.contractPhaseDesc = value;
    }

    /**
     * Gets the value of the currencyDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyDesc() {
        return currencyDesc;
    }

    /**
     * Sets the value of the currencyDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyDesc(String value) {
        this.currencyDesc = value;
    }

    /**
     * Gets the value of the cancellationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationFlag() {
        return cancellationFlag;
    }

    /**
     * Sets the value of the cancellationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationFlag(String value) {
        this.cancellationFlag = value;
    }

    /**
     * Gets the value of the mofLinkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOFLinkCode() {
        return mofLinkCode;
    }

    /**
     * Sets the value of the mofLinkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOFLinkCode(String value) {
        this.mofLinkCode = value;
    }

}
