//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AUE_ApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AUE_ApplicationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Instalment" type="{urn:crif-creditbureau:v1}InstalmentType"/&gt;
 *         &lt;element name="NonInstalment" type="{urn:crif-creditbureau:v1}NonInstalmentType"/&gt;
 *         &lt;element name="CreditCard" type="{urn:crif-creditbureau:v1}CreditCardType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ContractPhase" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ContractRequestDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MOFLinkCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AUE_ApplicationType", propOrder = {
    "instalment",
    "nonInstalment",
    "creditCard"
})
public class AUEApplicationType {

    @XmlElement(name = "Instalment")
    protected InstalmentType instalment;
    @XmlElement(name = "NonInstalment")
    protected NonInstalmentType nonInstalment;
    @XmlElement(name = "CreditCard")
    protected CreditCardType creditCard;
    @XmlAttribute(name = "ProductType")
    protected String productType;
    @XmlAttribute(name = "ContractPhase")
    protected String contractPhase;
    @XmlAttribute(name = "ContractRequestDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractRequestDate;
    @XmlAttribute(name = "Currency")
    protected String currency;
    @XmlAttribute(name = "MOFLinkCode")
    protected String mofLinkCode;

    /**
     * Gets the value of the instalment property.
     * 
     * @return
     *     possible object is
     *     {@link InstalmentType }
     *     
     */
    public InstalmentType getInstalment() {
        return instalment;
    }

    /**
     * Sets the value of the instalment property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstalmentType }
     *     
     */
    public void setInstalment(InstalmentType value) {
        this.instalment = value;
    }

    /**
     * Gets the value of the nonInstalment property.
     * 
     * @return
     *     possible object is
     *     {@link NonInstalmentType }
     *     
     */
    public NonInstalmentType getNonInstalment() {
        return nonInstalment;
    }

    /**
     * Sets the value of the nonInstalment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonInstalmentType }
     *     
     */
    public void setNonInstalment(NonInstalmentType value) {
        this.nonInstalment = value;
    }

    /**
     * Gets the value of the creditCard property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardType }
     *     
     */
    public CreditCardType getCreditCard() {
        return creditCard;
    }

    /**
     * Sets the value of the creditCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardType }
     *     
     */
    public void setCreditCard(CreditCardType value) {
        this.creditCard = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the contractPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractPhase() {
        return contractPhase;
    }

    /**
     * Sets the value of the contractPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractPhase(String value) {
        this.contractPhase = value;
    }

    /**
     * Gets the value of the contractRequestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractRequestDate() {
        return contractRequestDate;
    }

    /**
     * Sets the value of the contractRequestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractRequestDate(XMLGregorianCalendar value) {
        this.contractRequestDate = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the mofLinkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOFLinkCode() {
        return mofLinkCode;
    }

    /**
     * Sets the value of the mofLinkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOFLinkCode(String value) {
        this.mofLinkCode = value;
    }

}
