//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CB_AUE_ProductInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CB_AUE_ProductInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ApplicationToUpdate" type="{urn:crif-creditbureau:v1}ApplicationToUpdateType"/&gt;
 *         &lt;element name="ApplicationCodes" type="{urn:crif-creditbureau:v1}ApplicationCodesInputType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CB_AUE_ProductInputType", propOrder = {
    "applicationToUpdate",
    "applicationCodes"
})
public class CBAUEProductInputType {

    @XmlElement(name = "ApplicationToUpdate", required = true)
    protected ApplicationToUpdateType applicationToUpdate;
    @XmlElement(name = "ApplicationCodes", required = true)
    protected ApplicationCodesInputType applicationCodes;

    /**
     * Gets the value of the applicationToUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationToUpdateType }
     *     
     */
    public ApplicationToUpdateType getApplicationToUpdate() {
        return applicationToUpdate;
    }

    /**
     * Sets the value of the applicationToUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationToUpdateType }
     *     
     */
    public void setApplicationToUpdate(ApplicationToUpdateType value) {
        this.applicationToUpdate = value;
    }

    /**
     * Gets the value of the applicationCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationCodesInputType }
     *     
     */
    public ApplicationCodesInputType getApplicationCodes() {
        return applicationCodes;
    }

    /**
     * Sets the value of the applicationCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationCodesInputType }
     *     
     */
    public void setApplicationCodes(ApplicationCodesInputType value) {
        this.applicationCodes = value;
    }

}
