//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CB_ME_ProductOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CB_ME_ProductOutputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageId" type="{urn:crif-creditbureau:v1}MessageIdOutputType" minOccurs="0"/&gt;
 *         &lt;element name="EnquiredData" type="{urn:crif-creditbureau:v1}ME_EnquiredDataType" minOccurs="0"/&gt;
 *         &lt;element name="CreditReport" type="{urn:crif-creditbureau:v1}CreditReportType" minOccurs="0"/&gt;
 *         &lt;element name="CBScore" type="{urn:crif-creditbureau:v1}CBScoreType" minOccurs="0"/&gt;
 *         &lt;element name="Error" type="{urn:crif-creditbureau:v1}ErrorsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CB_ME_ProductOutputType", propOrder = {
    "messageId",
    "enquiredData",
    "creditReport",
    "cbScore",
    "error"
})
public class CBMEProductOutputType {

    @XmlElement(name = "MessageId")
    protected MessageIdOutputType messageId;
    @XmlElement(name = "EnquiredData")
    protected MEEnquiredDataType enquiredData;
    @XmlElement(name = "CreditReport")
    protected CreditReportType creditReport;
    @XmlElement(name = "CBScore")
    protected CBScoreType cbScore;
    @XmlElement(name = "Error")
    protected List<ErrorsType> error;

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link MessageIdOutputType }
     *     
     */
    public MessageIdOutputType getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageIdOutputType }
     *     
     */
    public void setMessageId(MessageIdOutputType value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the enquiredData property.
     * 
     * @return
     *     possible object is
     *     {@link MEEnquiredDataType }
     *     
     */
    public MEEnquiredDataType getEnquiredData() {
        return enquiredData;
    }

    /**
     * Sets the value of the enquiredData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEEnquiredDataType }
     *     
     */
    public void setEnquiredData(MEEnquiredDataType value) {
        this.enquiredData = value;
    }

    /**
     * Gets the value of the creditReport property.
     * 
     * @return
     *     possible object is
     *     {@link CreditReportType }
     *     
     */
    public CreditReportType getCreditReport() {
        return creditReport;
    }

    /**
     * Sets the value of the creditReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditReportType }
     *     
     */
    public void setCreditReport(CreditReportType value) {
        this.creditReport = value;
    }

    /**
     * Gets the value of the cbScore property.
     * 
     * @return
     *     possible object is
     *     {@link CBScoreType }
     *     
     */
    public CBScoreType getCBScore() {
        return cbScore;
    }

    /**
     * Sets the value of the cbScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBScoreType }
     *     
     */
    public void setCBScore(CBScoreType value) {
        this.cbScore = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorsType }
     * 
     * 
     */
    public List<ErrorsType> getError() {
        if (error == null) {
            error = new ArrayList<ErrorsType>();
        }
        return this.error;
    }

}
