//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CB_ME_ProductInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CB_ME_ProductInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CIS" type="{urn:crif-creditbureau:v1}ME_CISInputType"/&gt;
 *           &lt;element name="CISCodes" type="{urn:crif-creditbureau:v1}ME_CISCodesType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Purpose" type="{urn:crif-creditbureau:v1}PurposeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CB_ME_ProductInputType", propOrder = {
    "cis",
    "cisCodes",
    "purpose"
})
public class CBMEProductInputType {

    @XmlElement(name = "CIS")
    protected MECISInputType cis;
    @XmlElement(name = "CISCodes")
    protected MECISCodesType cisCodes;
    @XmlElement(name = "Purpose")
    protected PurposeType purpose;

    /**
     * Gets the value of the cis property.
     * 
     * @return
     *     possible object is
     *     {@link MECISInputType }
     *     
     */
    public MECISInputType getCIS() {
        return cis;
    }

    /**
     * Sets the value of the cis property.
     * 
     * @param value
     *     allowed object is
     *     {@link MECISInputType }
     *     
     */
    public void setCIS(MECISInputType value) {
        this.cis = value;
    }

    /**
     * Gets the value of the cisCodes property.
     * 
     * @return
     *     possible object is
     *     {@link MECISCodesType }
     *     
     */
    public MECISCodesType getCISCodes() {
        return cisCodes;
    }

    /**
     * Sets the value of the cisCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MECISCodesType }
     *     
     */
    public void setCISCodes(MECISCodesType value) {
        this.cisCodes = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link PurposeType }
     *     
     */
    public PurposeType getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurposeType }
     *     
     */
    public void setPurpose(PurposeType value) {
        this.purpose = value;
    }

}
