//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CB_NAE_ProductInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CB_NAE_ProductInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CIS" type="{urn:crif-creditbureau:v1}NAE_CISInputType"/&gt;
 *         &lt;element name="Application" type="{urn:crif-creditbureau:v1}ApplicationInputType" minOccurs="0"/&gt;
 *         &lt;element name="Link" type="{urn:crif-creditbureau:v1}LinkType"/&gt;
 *         &lt;element name="ApplicationCodes" type="{urn:crif-creditbureau:v1}ApplicationCodesInputType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CB_NAE_ProductInputType", propOrder = {
    "cis",
    "application",
    "link",
    "applicationCodes"
})
public class CBNAEProductInputType {

    @XmlElement(name = "CIS", required = true)
    protected NAECISInputType cis;
    @XmlElement(name = "Application")
    protected ApplicationInputType application;
    @XmlElement(name = "Link", required = true)
    protected LinkType link;
    @XmlElement(name = "ApplicationCodes", required = true)
    protected ApplicationCodesInputType applicationCodes;

    /**
     * Gets the value of the cis property.
     * 
     * @return
     *     possible object is
     *     {@link NAECISInputType }
     *     
     */
    public NAECISInputType getCIS() {
        return cis;
    }

    /**
     * Sets the value of the cis property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAECISInputType }
     *     
     */
    public void setCIS(NAECISInputType value) {
        this.cis = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationInputType }
     *     
     */
    public ApplicationInputType getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationInputType }
     *     
     */
    public void setApplication(ApplicationInputType value) {
        this.application = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType }
     *     
     */
    public LinkType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType }
     *     
     */
    public void setLink(LinkType value) {
        this.link = value;
    }

    /**
     * Gets the value of the applicationCodes property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationCodesInputType }
     *     
     */
    public ApplicationCodesInputType getApplicationCodes() {
        return applicationCodes;
    }

    /**
     * Sets the value of the applicationCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationCodesInputType }
     *     
     */
    public void setApplicationCodes(ApplicationCodesInputType value) {
        this.applicationCodes = value;
    }

}
