//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CBSGlocalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CBSGlocalType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="ScoreData" type="{urn:crif-creditbureau:v1}ScoreDataType" minOccurs="0"/&gt;
 *         &lt;element name="ExclusionRule" type="{urn:crif-creditbureau:v1}ExclusionRulesType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CBSGlocalType", propOrder = {
    "scoreData",
    "exclusionRule"
})
public class CBSGlocalType {

    @XmlElement(name = "ScoreData")
    protected ScoreDataType scoreData;
    @XmlElement(name = "ExclusionRule")
    protected ExclusionRulesType exclusionRule;

    /**
     * Gets the value of the scoreData property.
     * 
     * @return
     *     possible object is
     *     {@link ScoreDataType }
     *     
     */
    public ScoreDataType getScoreData() {
        return scoreData;
    }

    /**
     * Sets the value of the scoreData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScoreDataType }
     *     
     */
    public void setScoreData(ScoreDataType value) {
        this.scoreData = value;
    }

    /**
     * Gets the value of the exclusionRule property.
     * 
     * @return
     *     possible object is
     *     {@link ExclusionRulesType }
     *     
     */
    public ExclusionRulesType getExclusionRule() {
        return exclusionRule;
    }

    /**
     * Sets the value of the exclusionRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExclusionRulesType }
     *     
     */
    public void setExclusionRule(ExclusionRulesType value) {
        this.exclusionRule = value;
    }

}
