//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.06.07 at 04:47:12 PM BST
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CGRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CGRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}SubjectInputType" minOccurs="0"/&gt;
 *         &lt;element name="Link" type="{http://www.w3.org/2001/XMLSchema}LinkType" minOccurs="0"/&gt;
 *         &lt;element name="Application" type="{http://www.w3.org/2001/XMLSchema}ApplicationType" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationAdvanced" type="{http://www.w3.org/2001/XMLSchema}ApplicationAdvancedType" minOccurs="0"/&gt;
 *         &lt;element name="VehiclesData" type="{http://www.w3.org/2001/XMLSchema}VehiclesDataType" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationCode" type="{http://www.w3.org/2001/XMLSchema}ApplicationCodesInputType" minOccurs="0"/&gt;
 *         &lt;element name="Purpose" type="{http://www.w3.org/2001/XMLSchema}PurposeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CGRequestType", namespace="http://www.w3.org/2001/XMLSchema", propOrder = {
		"subject",
		"link",
		"application",
		"applicationAdvanced",
		"vehiclesData",
		"applicationCode",
		"purpose"
})
@XmlSeeAlso({
	CGRequest.class
})
public class CGRequestType {

	@XmlElement(name = "Subject")
	protected SubjectInputType subject;
	@XmlElement(name = "Link")
	protected LinkType link;
	@XmlElement(name = "Application")
	protected ApplicationType application;
	@XmlElement(name = "ApplicationAdvanced")
	protected ApplicationAdvancedType applicationAdvanced;
	@XmlElement(name = "VehiclesData")
	protected VehiclesDataType vehiclesData;
	@XmlElement(name = "ApplicationCode")
	protected ApplicationCodesInputType applicationCode;
	@XmlElement(name = "Purpose")
	protected PurposeType purpose;

	/**
	 * Gets the value of the subject property.
	 *
	 * @return
	 *     possible object is
	 *     {@link SubjectInputType }
	 *
	 */
	public SubjectInputType getSubject() {
		return subject;
	}

	/**
	 * Sets the value of the subject property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link SubjectInputType }
	 *
	 */
	public void setSubject(SubjectInputType value) {
		this.subject = value;
	}

	/**
	 * Gets the value of the link property.
	 *
	 * @return
	 *     possible object is
	 *     {@link LinkType }
	 *
	 */
	public LinkType getLink() {
		return link;
	}

	/**
	 * Sets the value of the link property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link LinkType }
	 *
	 */
	public void setLink(LinkType value) {
		this.link = value;
	}

	/**
	 * Gets the value of the application property.
	 *
	 * @return
	 *     possible object is
	 *     {@link ApplicationType }
	 *
	 */
	public ApplicationType getApplication() {
		return application;
	}

	/**
	 * Sets the value of the application property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link ApplicationType }
	 *
	 */
	public void setApplication(ApplicationType value) {
		this.application = value;
	}

	/**
	 * Gets the value of the applicationAdvanced property.
	 *
	 * @return
	 *     possible object is
	 *     {@link ApplicationAdvancedType }
	 *
	 */
	public ApplicationAdvancedType getApplicationAdvanced() {
		return applicationAdvanced;
	}

	/**
	 * Sets the value of the applicationAdvanced property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link ApplicationAdvancedType }
	 *
	 */
	public void setApplicationAdvanced(ApplicationAdvancedType value) {
		this.applicationAdvanced = value;
	}

	/**
	 * Gets the value of the vehiclesData property.
	 *
	 * @return
	 *     possible object is
	 *     {@link VehiclesDataType }
	 *
	 */
	public VehiclesDataType getVehiclesData() {
		return vehiclesData;
	}

	/**
	 * Sets the value of the vehiclesData property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link VehiclesDataType }
	 *
	 */
	public void setVehiclesData(VehiclesDataType value) {
		this.vehiclesData = value;
	}

	/**
	 * Gets the value of the applicationCode property.
	 *
	 * @return
	 *     possible object is
	 *     {@link ApplicationCodesInputType }
	 *
	 */
	public ApplicationCodesInputType getApplicationCode() {
		return applicationCode;
	}

	/**
	 * Sets the value of the applicationCode property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link ApplicationCodesInputType }
	 *
	 */
	public void setApplicationCode(ApplicationCodesInputType value) {
		this.applicationCode = value;
	}

	/**
	 * Gets the value of the purpose property.
	 *
	 * @return
	 *     possible object is
	 *     {@link PurposeType }
	 *
	 */
	public PurposeType getPurpose() {
		return purpose;
	}

	/**
	 * Sets the value of the purpose property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link PurposeType }
	 *
	 */
	public void setPurpose(PurposeType value) {
		this.purpose = value;
	}

}
