//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.06.07 at 04:47:12 PM BST
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.w3.org/2001/XMLSchema}CGRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Parameters" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DataSources" maxOccurs="unbounded">
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="FlowStep" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Order" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *                           &lt;attribute name="IntCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="PreCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="DeDup" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="CustomScore" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension>
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"parameters"
})
@XmlRootElement(name = "CGRequest", namespace="http://www.w3.org/2001/XMLSchema")
public class CGRequest
extends CGRequestType
{

	@XmlElement(name = "Parameters")
	protected CGRequest.Parameters parameters;

	/**
	 * Gets the value of the parameters property.
	 *
	 * @return
	 *     possible object is
	 *     {@link CGRequest.Parameters }
	 *
	 */
	public CGRequest.Parameters getParameters() {
		return parameters;
	}

	/**
	 * Sets the value of the parameters property.
	 *
	 * @param value
	 *     allowed object is
	 *     {@link CGRequest.Parameters }
	 *
	 */
	public void setParameters(CGRequest.Parameters value) {
		this.parameters = value;
	}


	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="DataSources" maxOccurs="unbounded">
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;attribute name="FlowStep" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
	 *                 &lt;attribute name="Order" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
	 *                 &lt;attribute name="IntCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
	 *                 &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *       &lt;attribute name="PreCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
	 *       &lt;attribute name="DeDup" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
	 *       &lt;attribute name="CustomScore" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"dataSources"
	})
	public static class Parameters {

		@XmlElement(name = "DataSources", required = true)
		protected List<CGRequest.Parameters.DataSources> dataSources;
		@XmlAttribute(name = "PreCheck")
		protected Boolean preCheck;
		@XmlAttribute(name = "DeDup")
		protected Boolean deDup;
		@XmlAttribute(name = "CustomScore")
		protected Boolean customScore;

		/**
		 * Gets the value of the dataSources property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the dataSources property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getDataSources().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link CGRequest.Parameters.DataSources }
		 *
		 *
		 */
		public List<CGRequest.Parameters.DataSources> getDataSources() {
			if (dataSources == null) {
				dataSources = new ArrayList<CGRequest.Parameters.DataSources>();
			}
			return this.dataSources;
		}

		/**
		 * Gets the value of the preCheck property.
		 *
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *
		 */
		public Boolean isPreCheck() {
			return preCheck;
		}

		/**
		 * Sets the value of the preCheck property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *
		 */
		public void setPreCheck(Boolean value) {
			this.preCheck = value;
		}

		/**
		 * Gets the value of the deDup property.
		 *
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *
		 */
		public Boolean isDeDup() {
			return deDup;
		}

		/**
		 * Sets the value of the deDup property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *
		 */
		public void setDeDup(Boolean value) {
			this.deDup = value;
		}

		/**
		 * Gets the value of the customScore property.
		 *
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *
		 */
		public Boolean isCustomScore() {
			return customScore;
		}

		/**
		 * Sets the value of the customScore property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *
		 */
		public void setCustomScore(Boolean value) {
			this.customScore = value;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;attribute name="FlowStep" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
		 *       &lt;attribute name="Order" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
		 *       &lt;attribute name="IntCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
		 *       &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class DataSources {

			@XmlAttribute(name = "FlowStep", required = true)
			protected String flowStep;
			@XmlAttribute(name = "Order")
			protected Long order;
			@XmlAttribute(name = "IntCheck")
			protected Boolean intCheck;
			@XmlAttribute(name = "Format")
			protected String format;

			/**
			 * Gets the value of the flowStep property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getFlowStep() {
				return flowStep;
			}

			/**
			 * Sets the value of the flowStep property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setFlowStep(String value) {
				this.flowStep = value;
			}

			/**
			 * Gets the value of the order property.
			 *
			 * @return
			 *     possible object is
			 *     {@link Long }
			 *
			 */
			public Long getOrder() {
				return order;
			}

			/**
			 * Sets the value of the order property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link Long }
			 *
			 */
			public void setOrder(Long value) {
				this.order = value;
			}

			/**
			 * Gets the value of the intCheck property.
			 *
			 * @return
			 *     possible object is
			 *     {@link Boolean }
			 *
			 */
			public Boolean isIntCheck() {
				return intCheck;
			}

			/**
			 * Sets the value of the intCheck property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link Boolean }
			 *
			 */
			public void setIntCheck(Boolean value) {
				this.intCheck = value;
			}

			/**
			 * Gets the value of the format property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getFormat() {
				return format;
			}

			/**
			 * Sets the value of the format property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setFormat(String value) {
				this.format = value;
			}

		}

	}

}
