//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ContractAlertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractAlertType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Instalment" type="{urn:crif-creditbureau:v1}InstallmentChangeType" minOccurs="0"/&gt;
 *         &lt;element name="NotInstalment" type="{urn:crif-creditbureau:v1}NotInstallmentChangeType" minOccurs="0"/&gt;
 *         &lt;element name="CreditCard" type="{urn:crif-creditbureau:v1}CreditCardChangeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CCRContractCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ProductType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ContractReferenceDate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractAlertType", propOrder = {
    "instalment",
    "notInstalment",
    "creditCard"
})
public class ContractAlertType {

    @XmlElement(name = "Instalment")
    protected InstallmentChangeType instalment;
    @XmlElement(name = "NotInstalment")
    protected NotInstallmentChangeType notInstalment;
    @XmlElement(name = "CreditCard")
    protected CreditCardChangeType creditCard;
    @XmlAttribute(name = "CCRContractCode", required = true)
    protected String ccrContractCode;
    @XmlAttribute(name = "ProductType", required = true)
    protected String productType;
    @XmlAttribute(name = "ContractReferenceDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar contractReferenceDate;

    /**
     * Gets the value of the instalment property.
     * 
     * @return
     *     possible object is
     *     {@link InstallmentChangeType }
     *     
     */
    public InstallmentChangeType getInstalment() {
        return instalment;
    }

    /**
     * Sets the value of the instalment property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallmentChangeType }
     *     
     */
    public void setInstalment(InstallmentChangeType value) {
        this.instalment = value;
    }

    /**
     * Gets the value of the notInstalment property.
     * 
     * @return
     *     possible object is
     *     {@link NotInstallmentChangeType }
     *     
     */
    public NotInstallmentChangeType getNotInstalment() {
        return notInstalment;
    }

    /**
     * Sets the value of the notInstalment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotInstallmentChangeType }
     *     
     */
    public void setNotInstalment(NotInstallmentChangeType value) {
        this.notInstalment = value;
    }

    /**
     * Gets the value of the creditCard property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardChangeType }
     *     
     */
    public CreditCardChangeType getCreditCard() {
        return creditCard;
    }

    /**
     * Sets the value of the creditCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardChangeType }
     *     
     */
    public void setCreditCard(CreditCardChangeType value) {
        this.creditCard = value;
    }

    /**
     * Gets the value of the ccrContractCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCRContractCode() {
        return ccrContractCode;
    }

    /**
     * Sets the value of the ccrContractCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCRContractCode(String value) {
        this.ccrContractCode = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the contractReferenceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractReferenceDate() {
        return contractReferenceDate;
    }

    /**
     * Sets the value of the contractReferenceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractReferenceDate(XMLGregorianCalendar value) {
        this.contractReferenceDate = value;
    }

}
