//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditCardsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditCardsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="NumbersSummary" type="{urn:crif-creditbureau:v1}NumbersSummaryType" minOccurs="0"/&gt;
 *         &lt;element name="AmountsSummary" type="{urn:crif-creditbureau:v1}CardsAmountsSummaryType" minOccurs="0"/&gt;
 *         &lt;element name="NotGrantedContract" type="{urn:crif-creditbureau:v1}CreditCardsNotGrantedType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="GrantedContract" type="{urn:crif-creditbureau:v1}CreditCardsGrantedType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditCardsType", propOrder = {
    "numbersSummary",
    "amountsSummary",
    "notGrantedContract",
    "grantedContract"
})
public class CreditCardsType {

    @XmlElement(name = "NumbersSummary")
    protected NumbersSummaryType numbersSummary;
    @XmlElement(name = "AmountsSummary")
    protected CardsAmountsSummaryType amountsSummary;
    @XmlElement(name = "NotGrantedContract")
    protected List<CreditCardsNotGrantedType> notGrantedContract;
    @XmlElement(name = "GrantedContract")
    protected List<CreditCardsGrantedType> grantedContract;

    /**
     * Gets the value of the numbersSummary property.
     * 
     * @return
     *     possible object is
     *     {@link NumbersSummaryType }
     *     
     */
    public NumbersSummaryType getNumbersSummary() {
        return numbersSummary;
    }

    /**
     * Sets the value of the numbersSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumbersSummaryType }
     *     
     */
    public void setNumbersSummary(NumbersSummaryType value) {
        this.numbersSummary = value;
    }

    /**
     * Gets the value of the amountsSummary property.
     * 
     * @return
     *     possible object is
     *     {@link CardsAmountsSummaryType }
     *     
     */
    public CardsAmountsSummaryType getAmountsSummary() {
        return amountsSummary;
    }

    /**
     * Sets the value of the amountsSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardsAmountsSummaryType }
     *     
     */
    public void setAmountsSummary(CardsAmountsSummaryType value) {
        this.amountsSummary = value;
    }

    /**
     * Gets the value of the notGrantedContract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notGrantedContract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotGrantedContract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditCardsNotGrantedType }
     * 
     * 
     */
    public List<CreditCardsNotGrantedType> getNotGrantedContract() {
        if (notGrantedContract == null) {
            notGrantedContract = new ArrayList<CreditCardsNotGrantedType>();
        }
        return this.notGrantedContract;
    }

    /**
     * Gets the value of the grantedContract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grantedContract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrantedContract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditCardsGrantedType }
     * 
     * 
     */
    public List<CreditCardsGrantedType> getGrantedContract() {
        if (grantedContract == null) {
            grantedContract = new ArrayList<CreditCardsGrantedType>();
        }
        return this.grantedContract;
    }

}
