//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditReportType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MatchedCIS" type="{urn:crif-creditbureau:v1}MatchedCISType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="ContractsHistory" type="{urn:crif-creditbureau:v1}ContractsHistoryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditReportType", propOrder = {
    "matchedCIS",
    "contractsHistory"
})
public class CreditReportType {

    @XmlElement(name = "MatchedCIS", required = true)
    protected List<MatchedCISType> matchedCIS;
    @XmlElement(name = "ContractsHistory")
    protected ContractsHistoryType contractsHistory;

    /**
     * Gets the value of the matchedCIS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matchedCIS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatchedCIS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MatchedCISType }
     * 
     * 
     */
    public List<MatchedCISType> getMatchedCIS() {
        if (matchedCIS == null) {
            matchedCIS = new ArrayList<MatchedCISType>();
        }
        return this.matchedCIS;
    }

    /**
     * Gets the value of the contractsHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ContractsHistoryType }
     *     
     */
    public ContractsHistoryType getContractsHistory() {
        return contractsHistory;
    }

    /**
     * Sets the value of the contractsHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractsHistoryType }
     *     
     */
    public void setContractsHistory(ContractsHistoryType value) {
        this.contractsHistory = value;
    }

}
