//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 04:47:12 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EmploymentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmploymentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="EmployerType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EmploymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EmploymentStartingDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="YearsEmployment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MonthsEmployment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="YearsOfEstabilishmentSoleTrader" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmploymentType")
public class EmploymentType {

    @XmlAttribute(name = "EmployerType")
    protected String employerType;
    @XmlAttribute(name = "EmploymentType")
    protected String employmentType;
    @XmlAttribute(name = "EmploymentStartingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar employmentStartingDate;
    @XmlAttribute(name = "YearsEmployment")
    protected String yearsEmployment;
    @XmlAttribute(name = "MonthsEmployment")
    protected String monthsEmployment;
    @XmlAttribute(name = "YearsOfEstabilishmentSoleTrader")
    protected String yearsOfEstabilishmentSoleTrader;

    /**
     * Gets the value of the employerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerType() {
        return employerType;
    }

    /**
     * Sets the value of the employerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerType(String value) {
        this.employerType = value;
    }

    /**
     * Gets the value of the employmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * Sets the value of the employmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentType(String value) {
        this.employmentType = value;
    }

    /**
     * Gets the value of the employmentStartingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEmploymentStartingDate() {
        return employmentStartingDate;
    }

    /**
     * Sets the value of the employmentStartingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEmploymentStartingDate(XMLGregorianCalendar value) {
        this.employmentStartingDate = value;
    }

    /**
     * Gets the value of the yearsEmployment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearsEmployment() {
        return yearsEmployment;
    }

    /**
     * Sets the value of the yearsEmployment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearsEmployment(String value) {
        this.yearsEmployment = value;
    }

    /**
     * Gets the value of the monthsEmployment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthsEmployment() {
        return monthsEmployment;
    }

    /**
     * Sets the value of the monthsEmployment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthsEmployment(String value) {
        this.monthsEmployment = value;
    }

    /**
     * Gets the value of the yearsOfEstabilishmentSoleTrader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearsOfEstabilishmentSoleTrader() {
        return yearsOfEstabilishmentSoleTrader;
    }

    /**
     * Sets the value of the yearsOfEstabilishmentSoleTrader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearsOfEstabilishmentSoleTrader(String value) {
        this.yearsOfEstabilishmentSoleTrader = value;
    }

}
