//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for IdentificationCodeMatchedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationCodeMatchedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="IdentificationCode" type="{urn:crif-creditbureau:v1}IdentificationCodeType"/&gt;
 *         &lt;element name="IdentificationCodeDesc" type="{urn:crif-creditbureau:v1}IdentificationCodeDescType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationCodeMatchedType", propOrder = {
    "identificationCode",
    "identificationCodeDesc"
})
public class IdentificationCodeMatchedType {

    @XmlElement(name = "IdentificationCode")
    protected IdentificationCodeType identificationCode;
    @XmlElement(name = "IdentificationCodeDesc")
    protected IdentificationCodeDescType identificationCodeDesc;
    @XmlAttribute(name = "LastUpdateDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdateDate;

    /**
     * Gets the value of the identificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationCodeType }
     *     
     */
    public IdentificationCodeType getIdentificationCode() {
        return identificationCode;
    }

    /**
     * Sets the value of the identificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationCodeType }
     *     
     */
    public void setIdentificationCode(IdentificationCodeType value) {
        this.identificationCode = value;
    }

    /**
     * Gets the value of the identificationCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationCodeDescType }
     *     
     */
    public IdentificationCodeDescType getIdentificationCodeDesc() {
        return identificationCodeDesc;
    }

    /**
     * Sets the value of the identificationCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationCodeDescType }
     *     
     */
    public void setIdentificationCodeDesc(IdentificationCodeDescType value) {
        this.identificationCodeDesc = value;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdateDate(XMLGregorianCalendar value) {
        this.lastUpdateDate = value;
    }

}
