//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for IndividualMatchedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualMatchedType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IndividualName" type="{urn:crif-creditbureau:v1}IndividualNameType" minOccurs="0"/&gt;
 *         &lt;element name="BirthData" type="{urn:crif-creditbureau:v1}BirthDataOutputType" minOccurs="0"/&gt;
 *         &lt;element name="AddressHistory" type="{urn:crif-creditbureau:v1}AddressHistoryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SoleTraderData" type="{urn:crif-creditbureau:v1}SoleTraderDataMatchedType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SuspectImpersonation" type="{urn:crif-creditbureau:v1}SuspectImpersonationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="GenderDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DeceasedAlert" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="DeceasedAlertDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualMatchedType", propOrder = {
    "individualName",
    "birthData",
    "addressHistory",
    "soleTraderData",
    "suspectImpersonation"
})
public class IndividualMatchedType {

    @XmlElement(name = "IndividualName")
    protected IndividualNameType individualName;
    @XmlElement(name = "BirthData")
    protected BirthDataOutputType birthData;
    @XmlElement(name = "AddressHistory")
    protected List<AddressHistoryType> addressHistory;
    @XmlElement(name = "SoleTraderData")
    protected List<SoleTraderDataMatchedType> soleTraderData;
    @XmlElement(name = "SuspectImpersonation")
    protected SuspectImpersonationType suspectImpersonation;
    @XmlAttribute(name = "Gender")
    protected String gender;
    @XmlAttribute(name = "GenderDesc")
    protected String genderDesc;
    @XmlAttribute(name = "DeceasedAlert")
    protected String deceasedAlert;
    @XmlAttribute(name = "DeceasedAlertDesc")
    protected String deceasedAlertDesc;
    @XmlAttribute(name = "LastUpdateDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastUpdateDate;

    /**
     * Gets the value of the individualName property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualNameType }
     *     
     */
    public IndividualNameType getIndividualName() {
        return individualName;
    }

    /**
     * Sets the value of the individualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualNameType }
     *     
     */
    public void setIndividualName(IndividualNameType value) {
        this.individualName = value;
    }

    /**
     * Gets the value of the birthData property.
     * 
     * @return
     *     possible object is
     *     {@link BirthDataOutputType }
     *     
     */
    public BirthDataOutputType getBirthData() {
        return birthData;
    }

    /**
     * Sets the value of the birthData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthDataOutputType }
     *     
     */
    public void setBirthData(BirthDataOutputType value) {
        this.birthData = value;
    }

    /**
     * Gets the value of the addressHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressHistoryType }
     * 
     * 
     */
    public List<AddressHistoryType> getAddressHistory() {
        if (addressHistory == null) {
            addressHistory = new ArrayList<AddressHistoryType>();
        }
        return this.addressHistory;
    }

    /**
     * Gets the value of the soleTraderData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the soleTraderData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoleTraderData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoleTraderDataMatchedType }
     * 
     * 
     */
    public List<SoleTraderDataMatchedType> getSoleTraderData() {
        if (soleTraderData == null) {
            soleTraderData = new ArrayList<SoleTraderDataMatchedType>();
        }
        return this.soleTraderData;
    }

    /**
     * Gets the value of the suspectImpersonation property.
     * 
     * @return
     *     possible object is
     *     {@link SuspectImpersonationType }
     *     
     */
    public SuspectImpersonationType getSuspectImpersonation() {
        return suspectImpersonation;
    }

    /**
     * Sets the value of the suspectImpersonation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuspectImpersonationType }
     *     
     */
    public void setSuspectImpersonation(SuspectImpersonationType value) {
        this.suspectImpersonation = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the genderDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenderDesc() {
        return genderDesc;
    }

    /**
     * Sets the value of the genderDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenderDesc(String value) {
        this.genderDesc = value;
    }

    /**
     * Gets the value of the deceasedAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeceasedAlert() {
        return deceasedAlert;
    }

    /**
     * Sets the value of the deceasedAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeceasedAlert(String value) {
        this.deceasedAlert = value;
    }

    /**
     * Gets the value of the deceasedAlertDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeceasedAlertDesc() {
        return deceasedAlertDesc;
    }

    /**
     * Sets the value of the deceasedAlertDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeceasedAlertDesc(String value) {
        this.deceasedAlertDesc = value;
    }

    /**
     * Gets the value of the lastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * Sets the value of the lastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdateDate(XMLGregorianCalendar value) {
        this.lastUpdateDate = value;
    }

}
