//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndividualInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IndividualName" type="{urn:crif-creditbureau:v1}IndividualNameType" minOccurs="0"/&gt;
 *         &lt;element name="BirthData" type="{urn:crif-creditbureau:v1}BirthDataInputType" minOccurs="0"/&gt;
 *         &lt;element name="Address" type="{urn:crif-creditbureau:v1}AddressType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="IdentificationCode" type="{urn:crif-creditbureau:v1}IdentificationCodeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Contact" type="{urn:crif-creditbureau:v1}ContactType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SoleTraderData" type="{urn:crif-creditbureau:v1}SoleTraderDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualInputType", propOrder = {
    "individualName",
    "birthData",
    "address",
    "identificationCode",
    "contact",
    "soleTraderData"
})
public class IndividualInputType {

    @XmlElement(name = "IndividualName")
    protected IndividualNameType individualName;
    @XmlElement(name = "BirthData")
    protected BirthDataInputType birthData;
    @XmlElement(name = "Address")
    protected List<AddressType> address;
    @XmlElement(name = "IdentificationCode")
    protected List<IdentificationCodeType> identificationCode;
    @XmlElement(name = "Contact")
    protected List<ContactType> contact;
    @XmlElement(name = "SoleTraderData")
    protected SoleTraderDataType soleTraderData;
    @XmlAttribute(name = "Gender")
    protected String gender;

    /**
     * Gets the value of the individualName property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualNameType }
     *     
     */
    public IndividualNameType getIndividualName() {
        return individualName;
    }

    /**
     * Sets the value of the individualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualNameType }
     *     
     */
    public void setIndividualName(IndividualNameType value) {
        this.individualName = value;
    }

    /**
     * Gets the value of the birthData property.
     * 
     * @return
     *     possible object is
     *     {@link BirthDataInputType }
     *     
     */
    public BirthDataInputType getBirthData() {
        return birthData;
    }

    /**
     * Sets the value of the birthData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthDataInputType }
     *     
     */
    public void setBirthData(BirthDataInputType value) {
        this.birthData = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the identificationCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationCodeType }
     * 
     * 
     */
    public List<IdentificationCodeType> getIdentificationCode() {
        if (identificationCode == null) {
            identificationCode = new ArrayList<IdentificationCodeType>();
        }
        return this.identificationCode;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactType }
     * 
     * 
     */
    public List<ContactType> getContact() {
        if (contact == null) {
            contact = new ArrayList<ContactType>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the soleTraderData property.
     * 
     * @return
     *     possible object is
     *     {@link SoleTraderDataType }
     *     
     */
    public SoleTraderDataType getSoleTraderData() {
        return soleTraderData;
    }

    /**
     * Sets the value of the soleTraderData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoleTraderDataType }
     *     
     */
    public void setSoleTraderData(SoleTraderDataType value) {
        this.soleTraderData = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

}
