//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkedCISType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkedCISType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="RoleOfCIS" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RoleOfCISDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkedCISType")
public class LinkedCISType {

    @XmlAttribute(name = "RoleOfCIS")
    protected String roleOfCIS;
    @XmlAttribute(name = "RoleOfCISDesc")
    protected String roleOfCISDesc;

    /**
     * Gets the value of the roleOfCIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleOfCIS() {
        return roleOfCIS;
    }

    /**
     * Sets the value of the roleOfCIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleOfCIS(String value) {
        this.roleOfCIS = value;
    }

    /**
     * Gets the value of the roleOfCISDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleOfCISDesc() {
        return roleOfCISDesc;
    }

    /**
     * Sets the value of the roleOfCISDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleOfCISDesc(String value) {
        this.roleOfCISDesc = value;
    }

}
