//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NAE_CISInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NAE_CISInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Individual" type="{urn:crif-creditbureau:v1}IndividualInputType"/&gt;
 *         &lt;element name="Company" type="{urn:crif-creditbureau:v1}CompanyInputType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="ProviderCISNo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NAE_CISInputType", propOrder = {
    "individual",
    "company"
})
public class NAECISInputType {

    @XmlElement(name = "Individual")
    protected IndividualInputType individual;
    @XmlElement(name = "Company")
    protected CompanyInputType company;
    @XmlAttribute(name = "ProviderCISNo")
    protected String providerCISNo;

    /**
     * Gets the value of the individual property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualInputType }
     *     
     */
    public IndividualInputType getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualInputType }
     *     
     */
    public void setIndividual(IndividualInputType value) {
        this.individual = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyInputType }
     *     
     */
    public CompanyInputType getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyInputType }
     *     
     */
    public void setCompany(CompanyInputType value) {
        this.company = value;
    }

    /**
     * Gets the value of the providerCISNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderCISNo() {
        return providerCISNo;
    }

    /**
     * Sets the value of the providerCISNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderCISNo(String value) {
        this.providerCISNo = value;
    }

}
