//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NAE_EnquiredDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NAE_EnquiredDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CIS" type="{urn:crif-creditbureau:v1}CISOutputType"/&gt;
 *         &lt;element name="Application" type="{urn:crif-creditbureau:v1}ApplicationType"/&gt;
 *         &lt;element name="ApplicationDesc" type="{urn:crif-creditbureau:v1}ApplicationDescType"/&gt;
 *         &lt;element name="Link" type="{urn:crif-creditbureau:v1}LinkType"/&gt;
 *         &lt;element name="LinkDesc" type="{urn:crif-creditbureau:v1}LinkDescType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CISRefDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NAE_EnquiredDataType", propOrder = {
    "cis",
    "application",
    "applicationDesc",
    "link",
    "linkDesc"
})
public class NAEEnquiredDataType {

    @XmlElement(name = "CIS", required = true)
    protected CISOutputType cis;
    @XmlElement(name = "Application", required = true)
    protected ApplicationType application;
    @XmlElement(name = "ApplicationDesc", required = true)
    protected ApplicationDescType applicationDesc;
    @XmlElement(name = "Link", required = true)
    protected LinkType link;
    @XmlElement(name = "LinkDesc", required = true)
    protected LinkDescType linkDesc;
    @XmlAttribute(name = "CISRefDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cisRefDate;

    /**
     * Gets the value of the cis property.
     * 
     * @return
     *     possible object is
     *     {@link CISOutputType }
     *     
     */
    public CISOutputType getCIS() {
        return cis;
    }

    /**
     * Sets the value of the cis property.
     * 
     * @param value
     *     allowed object is
     *     {@link CISOutputType }
     *     
     */
    public void setCIS(CISOutputType value) {
        this.cis = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationType }
     *     
     */
    public ApplicationType getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationType }
     *     
     */
    public void setApplication(ApplicationType value) {
        this.application = value;
    }

    /**
     * Gets the value of the applicationDesc property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationDescType }
     *     
     */
    public ApplicationDescType getApplicationDesc() {
        return applicationDesc;
    }

    /**
     * Sets the value of the applicationDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationDescType }
     *     
     */
    public void setApplicationDesc(ApplicationDescType value) {
        this.applicationDesc = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType }
     *     
     */
    public LinkType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType }
     *     
     */
    public void setLink(LinkType value) {
        this.link = value;
    }

    /**
     * Gets the value of the linkDesc property.
     * 
     * @return
     *     possible object is
     *     {@link LinkDescType }
     *     
     */
    public LinkDescType getLinkDesc() {
        return linkDesc;
    }

    /**
     * Sets the value of the linkDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkDescType }
     *     
     */
    public void setLinkDesc(LinkDescType value) {
        this.linkDesc = value;
    }

    /**
     * Gets the value of the cisRefDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCISRefDate() {
        return cisRefDate;
    }

    /**
     * Sets the value of the cisRefDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCISRefDate(XMLGregorianCalendar value) {
        this.cisRefDate = value;
    }

}
