//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonInstProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonInstProfileType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ReferenceYear" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="ReferenceMonth" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="CreditLimit" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="OutstandingBalance" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="OverdraftExcess" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="CreditStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CreditStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RestructureEvent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="RestructureEventDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonInstProfileType")
public class NonInstProfileType {

    @XmlAttribute(name = "ReferenceYear")
    protected BigInteger referenceYear;
    @XmlAttribute(name = "ReferenceMonth")
    protected BigInteger referenceMonth;
    @XmlAttribute(name = "CreditLimit")
    protected BigInteger creditLimit;
    @XmlAttribute(name = "OutstandingBalance")
    protected BigInteger outstandingBalance;
    @XmlAttribute(name = "OverdraftExcess")
    protected BigInteger overdraftExcess;
    @XmlAttribute(name = "CreditStatus")
    protected String creditStatus;
    @XmlAttribute(name = "CreditStatusDesc")
    protected String creditStatusDesc;
    @XmlAttribute(name = "RestructureEvent")
    protected String restructureEvent;
    @XmlAttribute(name = "RestructureEventDesc")
    protected String restructureEventDesc;

    /**
     * Gets the value of the referenceYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReferenceYear() {
        return referenceYear;
    }

    /**
     * Sets the value of the referenceYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReferenceYear(BigInteger value) {
        this.referenceYear = value;
    }

    /**
     * Gets the value of the referenceMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReferenceMonth() {
        return referenceMonth;
    }

    /**
     * Sets the value of the referenceMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReferenceMonth(BigInteger value) {
        this.referenceMonth = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreditLimit(BigInteger value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the outstandingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutstandingBalance() {
        return outstandingBalance;
    }

    /**
     * Sets the value of the outstandingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutstandingBalance(BigInteger value) {
        this.outstandingBalance = value;
    }

    /**
     * Gets the value of the overdraftExcess property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOverdraftExcess() {
        return overdraftExcess;
    }

    /**
     * Sets the value of the overdraftExcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOverdraftExcess(BigInteger value) {
        this.overdraftExcess = value;
    }

    /**
     * Gets the value of the creditStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditStatus() {
        return creditStatus;
    }

    /**
     * Sets the value of the creditStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditStatus(String value) {
        this.creditStatus = value;
    }

    /**
     * Gets the value of the creditStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditStatusDesc() {
        return creditStatusDesc;
    }

    /**
     * Sets the value of the creditStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditStatusDesc(String value) {
        this.creditStatusDesc = value;
    }

    /**
     * Gets the value of the restructureEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestructureEvent() {
        return restructureEvent;
    }

    /**
     * Sets the value of the restructureEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestructureEvent(String value) {
        this.restructureEvent = value;
    }

    /**
     * Gets the value of the restructureEventDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestructureEventDesc() {
        return restructureEventDesc;
    }

    /**
     * Sets the value of the restructureEventDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestructureEventDesc(String value) {
        this.restructureEventDesc = value;
    }

}
