//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 04:47:12 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rcibanque.rcidirect.clients.crif package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rcibanque.rcidirect.clients.crif
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CGRequest }
     * 
     */
    public CGRequest createCGRequest() {
        return new CGRequest();
    }

    /**
     * Create an instance of {@link CGRequest.Parameters }
     * 
     */
    public CGRequest.Parameters createCGRequestParameters() {
        return new CGRequest.Parameters();
    }

    /**
     * Create an instance of {@link SubjectInputType }
     * 
     */
    public SubjectInputType createSubjectInputType() {
        return new SubjectInputType();
    }

    /**
     * Create an instance of {@link CGRequestType }
     * 
     */
    public CGRequestType createCGRequestType() {
        return new CGRequestType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link ApplicationAdvancedType }
     * 
     */
    public ApplicationAdvancedType createApplicationAdvancedType() {
        return new ApplicationAdvancedType();
    }

    /**
     * Create an instance of {@link VehiclesDataType }
     * 
     */
    public VehiclesDataType createVehiclesDataType() {
        return new VehiclesDataType();
    }

    /**
     * Create an instance of {@link ApplicationCodesInputType }
     * 
     */
    public ApplicationCodesInputType createApplicationCodesInputType() {
        return new ApplicationCodesInputType();
    }

    /**
     * Create an instance of {@link PurposeType }
     * 
     */
    public PurposeType createPurposeType() {
        return new PurposeType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link EmploymentType }
     * 
     */
    public EmploymentType createEmploymentType() {
        return new EmploymentType();
    }

    /**
     * Create an instance of {@link PEPType }
     * 
     */
    public PEPType createPEPType() {
        return new PEPType();
    }

    /**
     * Create an instance of {@link CorporateDataType }
     * 
     */
    public CorporateDataType createCorporateDataType() {
        return new CorporateDataType();
    }

    /**
     * Create an instance of {@link IncomeExpensesType }
     * 
     */
    public IncomeExpensesType createIncomeExpensesType() {
        return new IncomeExpensesType();
    }

    /**
     * Create an instance of {@link InvidualDataType }
     * 
     */
    public InvidualDataType createInvidualDataType() {
        return new InvidualDataType();
    }

    /**
     * Create an instance of {@link SocioDemoDataType }
     * 
     */
    public SocioDemoDataType createSocioDemoDataType() {
        return new SocioDemoDataType();
    }

    /**
     * Create an instance of {@link CorporateType }
     * 
     */
    public CorporateType createCorporateType() {
        return new CorporateType();
    }

    /**
     * Create an instance of {@link SoleTraderDataType }
     * 
     */
    public SoleTraderDataType createSoleTraderDataType() {
        return new SoleTraderDataType();
    }

    /**
     * Create an instance of {@link TradeNameType }
     * 
     */
    public TradeNameType createTradeNameType() {
        return new TradeNameType();
    }

    /**
     * Create an instance of {@link IndividualType }
     * 
     */
    public IndividualType createIndividualType() {
        return new IndividualType();
    }

    /**
     * Create an instance of {@link AddressDataType }
     * 
     */
    public AddressDataType createAddressDataType() {
        return new AddressDataType();
    }

    /**
     * Create an instance of {@link IdentificationDataType }
     * 
     */
    public IdentificationDataType createIdentificationDataType() {
        return new IdentificationDataType();
    }

    /**
     * Create an instance of {@link CGRequest.Parameters.DataSources }
     * 
     */
    public CGRequest.Parameters.DataSources createCGRequestParametersDataSources() {
        return new CGRequest.Parameters.DataSources();
    }

    /**
     * Create an instance of {@link SubjectInputType.Individual }
     * 
     */
    public SubjectInputType.Individual createSubjectInputTypeIndividual() {
        return new SubjectInputType.Individual();
    }

}
