//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonalGuaranteeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalGuaranteeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="PersonalGuaranteeCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PersonalGuaranteeDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PersonalRecourseTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PersonalRecourseTypeCodeDesc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="PersonalRecourseAmount" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalGuaranteeType")
public class PersonalGuaranteeType {

    @XmlAttribute(name = "PersonalGuaranteeCode")
    protected String personalGuaranteeCode;
    @XmlAttribute(name = "PersonalGuaranteeDesc")
    protected String personalGuaranteeDesc;
    @XmlAttribute(name = "PersonalRecourseTypeCode")
    protected String personalRecourseTypeCode;
    @XmlAttribute(name = "PersonalRecourseTypeCodeDesc")
    protected String personalRecourseTypeCodeDesc;
    @XmlAttribute(name = "PersonalRecourseAmount")
    protected BigInteger personalRecourseAmount;

    /**
     * Gets the value of the personalGuaranteeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalGuaranteeCode() {
        return personalGuaranteeCode;
    }

    /**
     * Sets the value of the personalGuaranteeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalGuaranteeCode(String value) {
        this.personalGuaranteeCode = value;
    }

    /**
     * Gets the value of the personalGuaranteeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalGuaranteeDesc() {
        return personalGuaranteeDesc;
    }

    /**
     * Sets the value of the personalGuaranteeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalGuaranteeDesc(String value) {
        this.personalGuaranteeDesc = value;
    }

    /**
     * Gets the value of the personalRecourseTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalRecourseTypeCode() {
        return personalRecourseTypeCode;
    }

    /**
     * Sets the value of the personalRecourseTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalRecourseTypeCode(String value) {
        this.personalRecourseTypeCode = value;
    }

    /**
     * Gets the value of the personalRecourseTypeCodeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalRecourseTypeCodeDesc() {
        return personalRecourseTypeCodeDesc;
    }

    /**
     * Sets the value of the personalRecourseTypeCodeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalRecourseTypeCodeDesc(String value) {
        this.personalRecourseTypeCodeDesc = value;
    }

    /**
     * Gets the value of the personalRecourseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersonalRecourseAmount() {
        return personalRecourseAmount;
    }

    /**
     * Sets the value of the personalRecourseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersonalRecourseAmount(BigInteger value) {
        this.personalRecourseAmount = value;
    }

}
