//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScoreDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScoreDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ScoreRaw" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ScoreRange" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScoreDataType")
public class ScoreDataType {

    @XmlAttribute(name = "ScoreRaw")
    @XmlSchemaType(name = "anySimpleType")
    protected String scoreRaw;
    @XmlAttribute(name = "ScoreRange")
    @XmlSchemaType(name = "anySimpleType")
    protected String scoreRange;

    /**
     * Gets the value of the scoreRaw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreRaw() {
        return scoreRaw;
    }

    /**
     * Sets the value of the scoreRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreRaw(String value) {
        this.scoreRaw = value;
    }

    /**
     * Gets the value of the scoreRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreRange() {
        return scoreRange;
    }

    /**
     * Sets the value of the scoreRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreRange(String value) {
        this.scoreRange = value;
    }

}
