//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 04:47:12 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubjectInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectInputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Individual" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.w3.org/2001/XMLSchema}IndividualType"&gt;
 *               &lt;/extension>
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Corporate" type="{http://www.w3.org/2001/XMLSchema}CorporateType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="ProviderSubjectID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="CCRSubjectID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectInputType", propOrder = {
    "individual",
    "corporate"
})
public class SubjectInputType {

    @XmlElement(name = "Individual")
    protected SubjectInputType.Individual individual;
    @XmlElement(name = "Corporate")
    protected CorporateType corporate;
    @XmlAttribute(name = "ProviderSubjectID")
    protected String providerSubjectID;
    @XmlAttribute(name = "CCRSubjectID")
    @XmlSchemaType(name = "anySimpleType")
    protected String ccrSubjectID;

    /**
     * Gets the value of the individual property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectInputType.Individual }
     *     
     */
    public SubjectInputType.Individual getIndividual() {
        return individual;
    }

    /**
     * Sets the value of the individual property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectInputType.Individual }
     *     
     */
    public void setIndividual(SubjectInputType.Individual value) {
        this.individual = value;
    }

    /**
     * Gets the value of the corporate property.
     * 
     * @return
     *     possible object is
     *     {@link CorporateType }
     *     
     */
    public CorporateType getCorporate() {
        return corporate;
    }

    /**
     * Sets the value of the corporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorporateType }
     *     
     */
    public void setCorporate(CorporateType value) {
        this.corporate = value;
    }

    /**
     * Gets the value of the providerSubjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderSubjectID() {
        return providerSubjectID;
    }

    /**
     * Sets the value of the providerSubjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderSubjectID(String value) {
        this.providerSubjectID = value;
    }

    /**
     * Gets the value of the ccrSubjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCRSubjectID() {
        return ccrSubjectID;
    }

    /**
     * Sets the value of the ccrSubjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCRSubjectID(String value) {
        this.ccrSubjectID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.w3.org/2001/XMLSchema}IndividualType"&gt;
     *     &lt;/extension>
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Individual
        extends IndividualType
    {


    }

}
