//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:24:21 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SuspectImpersonationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuspectImpersonationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImpersonationFlag" type="{urn:crif-creditbureau:v1}ImpersonationFlagType"/&gt;
 *         &lt;element name="ImpersonationFlagDesc" type="{urn:crif-creditbureau:v1}ImpersonationFlagDescType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuspectImpersonationType", propOrder = {
    "impersonationFlag",
    "impersonationFlagDesc"
})
public class SuspectImpersonationType {

    @XmlElement(name = "ImpersonationFlag", required = true)
    protected ImpersonationFlagType impersonationFlag;
    @XmlElement(name = "ImpersonationFlagDesc")
    protected ImpersonationFlagDescType impersonationFlagDesc;

    /**
     * Gets the value of the impersonationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link ImpersonationFlagType }
     *     
     */
    public ImpersonationFlagType getImpersonationFlag() {
        return impersonationFlag;
    }

    /**
     * Sets the value of the impersonationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpersonationFlagType }
     *     
     */
    public void setImpersonationFlag(ImpersonationFlagType value) {
        this.impersonationFlag = value;
    }

    /**
     * Gets the value of the impersonationFlagDesc property.
     * 
     * @return
     *     possible object is
     *     {@link ImpersonationFlagDescType }
     *     
     */
    public ImpersonationFlagDescType getImpersonationFlagDesc() {
        return impersonationFlagDesc;
    }

    /**
     * Sets the value of the impersonationFlagDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpersonationFlagDescType }
     *     
     */
    public void setImpersonationFlagDesc(ImpersonationFlagDescType value) {
        this.impersonationFlagDesc = value;
    }

}
