//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 04:47:12 PM BST 
//


package com.rcibanque.rcidirect.clients.crif.domain.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VehiclesDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehiclesDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="AssetType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="NewUsed" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Make" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Model" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Chassis" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VehicleRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="VehicleRegistrationDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="CarPrice" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehiclesDataType")
public class VehiclesDataType {

    @XmlAttribute(name = "AssetType")
    protected String assetType;
    @XmlAttribute(name = "NewUsed")
    protected String newUsed;
    @XmlAttribute(name = "Make")
    protected String make;
    @XmlAttribute(name = "Model")
    protected String model;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "Chassis")
    protected String chassis;
    @XmlAttribute(name = "VehicleRegistrationNumber")
    protected String vehicleRegistrationNumber;
    @XmlAttribute(name = "VehicleRegistrationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar vehicleRegistrationDate;
    @XmlAttribute(name = "CarPrice")
    protected String carPrice;

    /**
     * Gets the value of the assetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetType() {
        return assetType;
    }

    /**
     * Sets the value of the assetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetType(String value) {
        this.assetType = value;
    }

    /**
     * Gets the value of the newUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewUsed() {
        return newUsed;
    }

    /**
     * Sets the value of the newUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewUsed(String value) {
        this.newUsed = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the chassis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChassis() {
        return chassis;
    }

    /**
     * Sets the value of the chassis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChassis(String value) {
        this.chassis = value;
    }

    /**
     * Gets the value of the vehicleRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleRegistrationNumber() {
        return vehicleRegistrationNumber;
    }

    /**
     * Sets the value of the vehicleRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleRegistrationNumber(String value) {
        this.vehicleRegistrationNumber = value;
    }

    /**
     * Gets the value of the vehicleRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVehicleRegistrationDate() {
        return vehicleRegistrationDate;
    }

    /**
     * Sets the value of the vehicleRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVehicleRegistrationDate(XMLGregorianCalendar value) {
        this.vehicleRegistrationDate = value;
    }

    /**
     * Gets the value of the carPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarPrice() {
        return carPrice;
    }

    /**
     * Sets the value of the carPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarPrice(String value) {
        this.carPrice = value;
    }

}
